apiVersion: v1
kind: Service
metadata:
  name: componentsvc
  labels:
    app: component
spec:
  type: NodePort
  ports:
  - port: 8086
    protocol: TCP
    name: http
  selector:
    app: component
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: containerops-component
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: component
    spec:
      containers:
      - name: component
        imagePullPolicy: IfNotPresent
        image: component:latest
