title = "containerops config"
[daemon]
listenmode = "http"
[service]
checkImage = "http://localhost:8080/v2/images/check"
buildImage = "http://localhost:8080/v2/images/build"
[log]
level = "debug"
file = "./log/component.log"
append = false
[database]
driver = "mysql"
uri = "containerops:containerops@tcp(192.168.0.105:3306)/containerops?parseTime=true"
